import re

with open('opspulse-fixed (1).html', 'r', encoding='utf-8') as f:
    content = f.read()

start_marker = '<div class="dash-main-grid" style="display:flex;flex-direction:column;gap:14px;">'
end_marker = '<!-- ========== PAGE: INTELLIGENCE ========== -->'

# Build the new content
new_dashboard_content = '''<div class="dash-main-grid" style="display:flex;flex-direction:column;gap:14px;">
        
        <!-- 1. HERO BANNER: Net Incremental Revenue -->
        <div class="card" style="text-align:center; padding: 40px 20px; background: linear-gradient(135deg, var(--surface-solid) 0%, var(--surface-hover) 100%); border: 1px solid var(--border-md);">
          <div style="font-size: 13px; color: var(--text-secondary); text-transform: uppercase; letter-spacing: 1px; font-weight: 700; margin-bottom: 8px;">Net Incremental Revenue</div>
          <div style="font-size: 56px; font-weight: 800; color: var(--accent-green); font-family: var(--font-display); letter-spacing: -1.5px; text-shadow: 0 0 30px var(--accent-green-bg); line-height: 1;">+$0.00</div>
          <div style="font-size: 13px; color: var(--text-muted); margin-top: 12px; font-weight: 500;">Generated by ZenoAI this month</div>
        </div>

        <!-- 2. KPI CARDS -->
        <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px;">
          <!-- Analyzed Traffic -->
          <div class="card" style="border-top: 3px solid var(--accent-blue); padding: 20px;">
            <div style="font-size: 11px; color: var(--text-muted); text-transform: uppercase; font-weight: 700; margin-bottom: 8px; letter-spacing: 0.5px;">Analyzed Traffic</div>
            <div style="font-size: 26px; font-weight: 700; color: var(--text-primary); font-family: var(--font-display);">0</div>
            <div style="font-size: 11px; color: var(--text-secondary); margin-top: 6px; font-weight: 500;">Visitors examined</div>
          </div>
          <!-- Smart Interventions -->
          <div class="card" style="border-top: 3px solid var(--accent-purple); padding: 20px;">
            <div style="font-size: 11px; color: var(--text-muted); text-transform: uppercase; font-weight: 700; margin-bottom: 8px; letter-spacing: 0.5px;">Smart Interventions</div>
            <div style="font-size: 26px; font-weight: 700; color: var(--text-primary); font-family: var(--font-display);">0</div>
            <div style="font-size: 11px; color: var(--text-secondary); margin-top: 6px; font-weight: 500;">Actions taken</div>
          </div>
          <!-- Conversion Lift -->
          <div class="card" style="border-top: 3px solid var(--accent-green); padding: 20px;">
            <div style="font-size: 11px; color: var(--text-muted); text-transform: uppercase; font-weight: 700; margin-bottom: 8px; letter-spacing: 0.5px;">Conversion Lift</div>
            <div style="font-size: 26px; font-weight: 700; color: var(--text-primary); font-family: var(--font-display);">+0%</div>
            <div style="font-size: 11px; color: var(--text-secondary); margin-top: 6px; font-weight: 500;">Vs. baseline</div>
          </div>
          <!-- Margin Saved -->
          <div class="card" style="border-top: 3px solid var(--accent-yellow); padding: 20px;">
            <div style="font-size: 11px; color: var(--text-muted); text-transform: uppercase; font-weight: 700; margin-bottom: 8px; letter-spacing: 0.5px;">Margin Saved</div>
            <div style="font-size: 26px; font-weight: 700; color: var(--text-primary); font-family: var(--font-display);">$0.00</div>
            <div style="font-size: 11px; color: var(--text-secondary); margin-top: 6px; font-weight: 500;">Protected from discounts</div>
          </div>
        </div>

        <!-- 3. CHARTS & ENGINE GRID -->
        <div style="display: grid; grid-template-columns: 2fr 1fr; gap: 14px;">
          
          <!-- LEFT: LINE CHART -->
          <div class="card" style="display:flex; flex-direction:column;">
            <div class="section-header" style="margin-bottom: 16px;">
              <div class="section-title">Revenue: AI vs Holdout</div>
              <div style="display:flex; gap: 12px; font-size: 11px; font-weight: 600;">
                <span style="display:flex; align-items:center; gap:6px;"><span style="width:8px;height:8px;border-radius:50%;background:var(--accent-blue);"></span> AI Managed (80%)</span>
                <span style="display:flex; align-items:center; gap:6px;"><span style="width:8px;height:8px;border-radius:50%;background:var(--border-md);"></span> Natural Holdout (20%)</span>
              </div>
            </div>
            <!-- Zero State Line Chart -->
            <div style="flex: 1; min-height: 220px; position: relative; border-bottom: 1px solid var(--border); border-left: 1px solid var(--border); margin-top: 10px; margin-left: 20px; margin-bottom: 10px;">
              <!-- Y-Axis labels -->
              <div style="position:absolute; left:-25px; bottom:-6px; font-size:9px; color:var(--text-muted);">0</div>
              <div style="position:absolute; left:-25px; top:48%; font-size:9px; color:var(--text-muted);">5k</div>
              <div style="position:absolute; left:-25px; top:-6px; font-size:9px; color:var(--text-muted);">10k</div>
              <!-- Grid lines -->
              <div style="position:absolute; width:100%; height:1px; background:var(--border); opacity: 0.5; top:50%;"></div>
              
              <!-- Zero state flat lines -->
              <svg style="position:absolute; width:100%; height:100%; overflow: visible;" preserveAspectRatio="none" viewBox="0 0 100 100">
                 <!-- AI Line (Blue) -->
                 <polyline points="0,100 20,100 40,100 60,100 80,100 100,100" fill="none" stroke="var(--accent-blue)" stroke-width="2"/>
                 <!-- Holdout Line (Grey) -->
                 <polyline points="0,100 20,100 40,100 60,100 80,100 100,100" fill="none" stroke="var(--text-muted)" stroke-width="2" stroke-dasharray="2,2" opacity="0.6"/>
              </svg>
            </div>
          </div>

          <!-- RIGHT: DONUT & ENGINE -->
          <div style="display: flex; flex-direction: column; gap: 14px;">
            
            <!-- DONUT CHART (Visitor Intent) -->
            <div class="card" style="flex: 1;">
              <div class="section-title" style="margin-bottom: 16px;">Visitor Intent Distribution</div>
              <div style="display: flex; align-items: center; gap: 20px; height: 100%;">
                <div style="position:relative; width:90px; height:90px; border-radius:50%; background: conic-gradient(var(--border-md) 0% 100%);">
                  <div style="position:absolute; top:18px; left:18px; right:18px; bottom:18px; background:var(--surface-solid); border-radius:50%;"></div>
                </div>
                <div style="flex:1; display:flex; flex-direction:column; gap:10px;">
                  <div style="display:flex; justify-content:space-between; font-size:11px; font-weight: 600;"><span style="display:flex; align-items:center; gap:6px; color:var(--text-primary);"><span class="status-dot dot-green"></span> High Intent</span> <span style="color:var(--text-secondary);">0%</span></div>
                  <div style="display:flex; justify-content:space-between; font-size:11px; font-weight: 600;"><span style="display:flex; align-items:center; gap:6px; color:var(--text-primary);"><span class="status-dot dot-yellow"></span> Hesitant</span> <span style="color:var(--text-secondary);">0%</span></div>
                  <div style="display:flex; justify-content:space-between; font-size:11px; font-weight: 600;"><span style="display:flex; align-items:center; gap:6px; color:var(--text-primary);"><span class="status-dot" style="background:var(--border-md);"></span> Browsing</span> <span style="color:var(--text-secondary);">0%</span></div>
                </div>
              </div>
            </div>

            <!-- CONFIDENCE ENGINE -->
            <div class="card" style="flex: 1;">
              <div class="section-title" style="margin-bottom: 16px;">RTL Confidence Engine</div>
              <div style="display:flex; flex-direction:column; gap:12px;">
                <!-- Causal Confidence -->
                <div>
                  <div style="display:flex; justify-content:space-between; font-size:11px; margin-bottom:6px; font-weight:700;">
                    <span style="color:var(--text-primary);">Causal Confidence</span><span style="color:var(--accent-green);">0%</span>
                  </div>
                  <div style="height:6px; background:var(--border-md); border-radius:10px; overflow:hidden;">
                    <div style="height:100%; width:0%; background:var(--accent-green); transition:var(--transition);"></div>
                  </div>
                </div>
                <!-- Data Integrity -->
                <div>
                  <div style="display:flex; justify-content:space-between; font-size:11px; margin-bottom:6px; font-weight:700;">
                    <span style="color:var(--text-primary);">Data Integrity</span><span style="color:var(--accent-blue);">0%</span>
                  </div>
                  <div style="height:6px; background:var(--border-md); border-radius:10px; overflow:hidden;">
                    <div style="height:100%; width:0%; background:var(--accent-blue); transition:var(--transition);"></div>
                  </div>
                </div>
                <!-- Profit Protection -->
                <div>
                  <div style="display:flex; justify-content:space-between; font-size:11px; margin-bottom:6px; font-weight:700;">
                    <span style="color:var(--text-primary);">Profit Protection</span><span style="color:var(--accent-purple);">0%</span>
                  </div>
                  <div style="height:6px; background:var(--border-md); border-radius:10px; overflow:hidden;">
                    <div style="height:100%; width:0%; background:var(--accent-purple); transition:var(--transition);"></div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- 4. LIVE DECISION FEED -->
        <div class="activities-card">
          <div class="activities-header">
            <span class="activities-title">Live Decision Feed</span>
            <div style="display:flex;gap:8px;align-items:center;">
              <span style="font-size:11px; font-weight: 600; color:var(--text-muted); display:flex; align-items:center; gap:6px;"><span class="live-dot" style="width:6px; height:6px;"></span> Streaming</span>
            </div>
          </div>
          <table class="tbl">
            <thead>
              <tr>
                <th style="width: 15%;">Time</th>
                <th style="width: 20%;">Customer</th>
                <th style="width: 15%;">Intent</th>
                <th style="width: 35%;">System Decision</th>
                <th style="width: 15%;">Outcome</th>
              </tr>
            </thead>
            <tbody id="decision-feed-tbody">
              <tr><td colspan="5" style="text-align:center;padding:24px;color:var(--text-muted);font-size:12px;">No results</td></tr>
            </tbody>
          </table>
        </div>

      </div>
    </div>

    '''

# Replace
idx1 = content.find(start_marker)
idx2 = content.find(end_marker)

if idx1 > -1 and idx2 > -1:
    content = content[:idx1] + new_dashboard_content + content[idx2:]
    with open('opspulse-fixed (1).html', 'w', encoding='utf-8') as f:
        f.write(content)
    print("Dashboard replaced successfully.")
else:
    print("Markers not found.")
    print("idx1:", idx1)
    print("idx2:", idx2)
