import re

with open('opspulse-fixed (1).html', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. NEW HERO BANNER (5 Columns)
new_hero = '''<!-- 1. HERO BANNER: Net Incremental Revenue -->
        <div class="card" style="padding: 24px; background: linear-gradient(135deg, var(--surface-solid) 0%, var(--surface-hover) 100%); border: 1px solid var(--border-md);">
          <div style="font-size: 14px; font-weight: 700; color: var(--text-primary); margin-bottom: 20px;">Net Incremental Revenue <span style="font-weight:400; color:var(--text-muted); font-size:12px; margin-left:8px;">Generated by ZenoAI</span></div>
          <div style="display: flex; align-items: center; justify-content: space-between;">
            <!-- Today -->
            <div style="flex: 1; padding-right: 16px; border-right: 1px solid var(--border);">
              <div style="font-size: 11px; color: var(--text-muted); text-transform: uppercase; font-weight: 700; margin-bottom: 4px; letter-spacing: 0.5px;">Today</div>
              <div style="font-size: 32px; font-weight: 700; color: var(--text-primary); font-family: var(--font-display);">+$0.00</div>
            </div>
            <!-- This Week -->
            <div style="flex: 1; padding: 0 16px; border-right: 1px solid var(--border);">
              <div style="font-size: 11px; color: var(--text-muted); text-transform: uppercase; font-weight: 700; margin-bottom: 4px; letter-spacing: 0.5px;">This Week</div>
              <div style="font-size: 32px; font-weight: 700; color: var(--text-primary); font-family: var(--font-display);">+$0.00</div>
            </div>
            <!-- Total -->
            <div style="flex: 1; padding: 0 16px; border-right: 1px solid var(--border);">
              <div style="font-size: 11px; color: var(--text-muted); text-transform: uppercase; font-weight: 700; margin-bottom: 4px; letter-spacing: 0.5px;">Total Generated</div>
              <div style="font-size: 32px; font-weight: 700; color: var(--accent-green); font-family: var(--font-display);">+$0.00</div>
            </div>
            <!-- Percentage Increase -->
            <div style="flex: 1; padding: 0 16px; border-right: 1px solid var(--border);">
              <div style="font-size: 11px; color: var(--text-muted); text-transform: uppercase; font-weight: 700; margin-bottom: 4px; letter-spacing: 0.5px;">Revenue Lift</div>
              <div style="font-size: 32px; font-weight: 700; color: var(--text-primary); font-family: var(--font-display);">+0%</div>
            </div>
            <!-- Analyzed Today -->
            <div style="flex: 1; padding-left: 16px;">
              <div style="font-size: 11px; color: var(--text-muted); text-transform: uppercase; font-weight: 700; margin-bottom: 4px; letter-spacing: 0.5px;">Analyzed Today</div>
              <div style="font-size: 32px; font-weight: 700; color: var(--text-primary); font-family: var(--font-display);">0</div>
            </div>
          </div>
        </div>'''

# Replace Hero Banner
content = re.sub(r'<!-- 1\. HERO BANNER:.*?</div>\s+</div>\s+</div>', new_hero, content, flags=re.DOTALL)

# 2. NEW LIVE DECISION FEED
new_feed = '''<!-- 4. LIVE DECISION FEED -->
        <div class="card" style="padding: 0; overflow: hidden;">
          <div style="padding: 16px 20px; border-bottom: 1px solid var(--border); display: flex; justify-content: space-between; align-items: center; background: var(--surface-hover);">
            <div style="font-size: 14px; font-weight: 700; color: var(--text-primary); display: flex; align-items: center; gap: 8px;">
              <span class="live-dot" style="width: 8px; height: 8px; background: var(--accent-green);"></span> Real-Time Decision Feed
            </div>
            <button class="btn-sm btn-sm-outline" style="display:flex;align-items:center;gap:6px; font-size:11px; padding:4px 10px;">
              <svg width="10" height="10" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="2" width="2" height="10"/><rect x="9" y="2" width="2" height="10"/></svg> Pause
            </button>
          </div>
          
          <div style="display: flex; flex-direction: column;" id="realtime-feed-list">
            
            <!-- Item 1 (Accepted/Converted) -->
            <div style="display: flex; align-items: center; justify-content: space-between; padding: 12px 20px; border-bottom: 1px solid var(--border-md);">
              <div style="display: flex; align-items: center; gap: 12px; flex: 1;">
                <span style="font-family: var(--mono); font-size: 12px; color: var(--text-secondary);">sess_x7y8z</span>
                <span style="color: var(--text-muted);">→</span>
                <span style="font-size: 12px; color: var(--text-muted); width: 100px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;" title="/cart">/cart</span>
                <span style="color: var(--text-muted);">→</span>
                <span class="badge" style="background: rgba(245,197,24,0.1); color: var(--accent-yellow); border: 1px solid rgba(245,197,24,0.2); font-family: var(--mono); font-weight: 600; padding: 4px 8px;">discount_10%</span>
                <span style="font-size: 13px; color: var(--text-secondary); margin-left: 8px;">triggered (conf:0.74) <span style="color: var(--text-muted); margin: 0 4px;">→</span> <span style="color: var(--accent-green);">converted ✓</span></span>
              </div>
              <div style="font-family: var(--mono); font-size: 14px; font-weight: 700; color: var(--accent-green);">+$0.00</div>
            </div>

            <!-- Item 2 (Pending) -->
            <div style="display: flex; align-items: center; justify-content: space-between; padding: 12px 20px; border-bottom: 1px solid var(--border-md);">
              <div style="display: flex; align-items: center; gap: 12px; flex: 1;">
                <span style="font-family: var(--mono); font-size: 12px; color: var(--text-secondary);">sess_3d7b1</span>
                <span style="color: var(--text-muted);">→</span>
                <span style="font-size: 12px; color: var(--text-muted); width: 100px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;" title="/checkout">/checkout</span>
                <span style="color: var(--text-muted);">→</span>
                <span class="badge" style="background: rgba(37,99,235,0.1); color: var(--accent-blue); border: 1px solid rgba(37,99,235,0.2); font-family: var(--mono); font-weight: 600; padding: 4px 8px;">urgency_popup</span>
                <span style="font-size: 13px; color: var(--text-secondary); margin-left: 8px;">shown (hes:0.65 conf:0.73)</span>
              </div>
              <div style="font-family: var(--font); font-size: 13px; font-weight: 700; color: var(--accent-orange);">pending</div>
            </div>

            <!-- Item 3 (Rejected/Do Nothing) -->
            <div style="display: flex; align-items: center; justify-content: space-between; padding: 12px 20px;">
              <div style="display: flex; align-items: center; gap: 12px; flex: 1;">
                <span style="font-family: var(--mono); font-size: 12px; color: var(--text-secondary);">sess_a1c5e</span>
                <span style="color: var(--text-muted);">→</span>
                <span style="font-size: 12px; color: var(--text-muted); width: 100px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;" title="/product/shoes">/product/shoes</span>
                <span style="color: var(--text-muted);">→</span>
                <span class="badge" style="background: rgba(154,154,150,0.1); color: var(--text-secondary); border: 1px solid rgba(154,154,150,0.2); font-family: var(--mono); font-weight: 600; padding: 4px 8px;">do_nothing</span>
                <span style="font-size: 13px; color: var(--text-secondary); margin-left: 8px;">— confidence 0.42 below threshold</span>
              </div>
              <div style="font-family: var(--mono); font-size: 14px; font-weight: 700; color: var(--text-muted);">—</div>
            </div>

          </div>
        </div>'''

# Replace Decision Feed
content = re.sub(r'<!-- 4\. LIVE DECISION FEED -->.*?</table>\s+</div>', new_feed, content, flags=re.DOTALL)

with open('opspulse-fixed (1).html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Hero Banner and Decision Feed updated.")
