"use client";
import React, { useState } from "react";
import { Zap, Shield, CheckCircle, Brain, ArrowRight, Lock } from "lucide-react";
import { useRouter } from "next/navigation";

export default function PricingPage() {
  const router = useRouter();
  const [loadingPlan, setLoadingPlan] = useState<string | null>(null);

  const startCheckout = async (planKey: string) => {
    setLoadingPlan(planKey);
    try {
      const res = await fetch("/api/billing/checkout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ plan: planKey })
      });
      const data = await res.json();
      if (data.url) {
        window.location.href = data.url;
      } else {
        alert(data.error || "Failed to initiate checkout");
        setLoadingPlan(null);
      }
    } catch (err) {
      alert("Error connecting to billing engine");
      setLoadingPlan(null);
    }
  };

  return (
    <div className="min-h-screen bg-[#000000] text-white font-sans selection:bg-[#00ff66] selection:text-black">
      
      {/* HEADER NAV */}
      <nav className="flex items-center justify-between px-8 py-6 border-b border-[#222]">
        <div className="flex items-center gap-3">
          <div className="flex items-end h-8">
            <div className="w-2 h-5 bg-[#00ff66] rounded-sm mr-1"></div>
            <div className="w-2 h-7 bg-white rounded-sm mr-1"></div>
            <div className="w-2 h-9 bg-white rounded-sm"></div>
          </div>
          <span className="text-xl font-bold tracking-widest uppercase">NOLIX</span>
        </div>
        <div className="flex items-center gap-2">
          <Lock size={16} className="text-gray-500" />
          <span className="text-gray-400 font-mono text-sm">Secure Payment Gateway</span>
        </div>
      </nav>

      {/* HERO */}
      <main className="max-w-6xl mx-auto px-6 py-20 text-center">
        <h1 className="text-4xl md:text-6xl font-black mb-6 tracking-tight">
          We Only Win When <span className="text-[#00ff66] drop-shadow-[0_0_15px_rgba(0,255,102,0.4)]">You Win.</span>
        </h1>
        <p className="text-xl text-gray-400 mb-8 max-w-3xl mx-auto leading-relaxed">
          The Hybrid Revenue Model. You pay a baseline subscription for the infrastructure, plus a performance share strictly 
          on <strong className="text-white">incremental revenue directly generated by the AI</strong>. Zero risk.
        </p>
        
        <div className="mb-16 inline-block p-4 bg-[#00ff66]/10 border border-[#00ff66]/30 rounded-xl shadow-[0_0_20px_rgba(0,255,102,0.15)] transform hover:scale-105 transition-transform cursor-default">
          <p className="text-[#00ff66] font-mono font-bold text-lg tracking-wide uppercase">
            👉 "If we generate <span className="text-white">$5,000</span> → you pay <span className="text-white">$1,000</span>."
          </p>
          <p className="text-[#00ff66]/70 font-mono text-sm mt-1">If we generate $0, you pay $0 in performance share.</p>
        </div>

        {/* PRICING PLANS */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-left mb-20">
          
          {/* STARTER */}
          <div className="bg-[#050805] border border-[#222] rounded-3xl p-8 shadow-[0_0_20px_rgba(0,0,0,0.5)] flex flex-col justify-between group hover:border-[#00ff66]/40 transition-colors">
            <div>
              <h3 className="text-2xl font-bold text-white mb-2">Starter</h3>
              <p className="text-gray-400 text-sm mb-6 h-10">For nascent stores below $50k/mo seeking automated conversion lift.</p>
              
              <div className="my-6 space-y-1">
                <div className="text-5xl font-black text-white tracking-tighter">$99<span className="text-xl text-gray-500 font-normal">/mo</span></div>
                <div className="text-[#00ff66] font-bold text-lg">+ 10% Performance Share</div>
              </div>

              <ul className="space-y-4 mb-8">
                <li className="flex items-start gap-3"><CheckCircle size={20} className="text-[#00ff66] shrink-0 mt-0.5" /> <span className="text-gray-300 text-sm">Standard Causal Modeling</span></li>
                <li className="flex items-start gap-3"><CheckCircle size={20} className="text-[#00ff66] shrink-0 mt-0.5" /> <span className="text-gray-300 text-sm">Real-time Revenue Interception</span></li>
                <li className="flex items-start gap-3"><CheckCircle size={20} className="text-[#00ff66] shrink-0 mt-0.5" /> <span className="text-gray-300 text-sm">Automated Discount Protection</span></li>
              </ul>
            </div>
            
            <button 
              onClick={() => startCheckout("starter")}
              disabled={loadingPlan !== null}
              className="w-full py-4 bg-[#111] hover:bg-[#222] text-white font-bold rounded-full border border-[#333] transition-colors flex items-center justify-center gap-2"
            >
              {loadingPlan === "starter" ? "Initiating..." : "Start Increasing Revenue"} <ArrowRight size={18} />
            </button>
          </div>

          {/* GROWTH (HIGHLIGHTED) */}
          <div className="bg-[#0a150a] border border-[#00ff66]/50 rounded-3xl p-8 shadow-[0_0_40px_rgba(0,255,102,0.1)] flex flex-col justify-between relative transform md:-translate-y-4">
            <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-[#00ff66] text-black font-black text-xs uppercase tracking-widest px-4 py-1.5 rounded-full">
              Most Popular
            </div>
            
            <div>
              <h3 className="text-2xl font-bold text-white mb-2">Growth</h3>
              <p className="text-gray-400 text-sm mb-6 h-10">For scaling brands requiring deep AI-driven margin preservation.</p>
              
              <div className="my-6 space-y-1">
                <div className="text-5xl font-black text-[#00ff66] drop-shadow-[0_0_10px_rgba(0,255,102,0.3)] tracking-tighter">$199<span className="text-xl text-gray-500 font-normal">/mo</span></div>
                <div className="text-white font-bold text-lg">+ 20% Performance Share</div>
              </div>

              <ul className="space-y-4 mb-8">
                <li className="flex items-start gap-3"><CheckCircle size={20} className="text-[#00ff66] shrink-0 mt-0.5" /> <span className="text-gray-200 text-sm font-bold">Everything in Starter</span></li>
                <li className="flex items-start gap-3"><CheckCircle size={20} className="text-[#00ff66] shrink-0 mt-0.5" /> <span className="text-gray-300 text-sm">A/B Traffic Routing Engine</span></li>
                <li className="flex items-start gap-3"><CheckCircle size={20} className="text-[#00ff66] shrink-0 mt-0.5" /> <span className="text-gray-300 text-sm">Deep Market Intelligence Logs</span></li>
                <li className="flex items-start gap-3"><CheckCircle size={20} className="text-[#00ff66] shrink-0 mt-0.5" /> <span className="text-gray-300 text-sm">Priority Stripe Usage Sync</span></li>
              </ul>
            </div>
            
            <button 
              onClick={() => startCheckout("growth")}
              disabled={loadingPlan !== null}
              className="w-full py-4 bg-gradient-to-r from-[#1eff56] to-[#0fdc40] text-black font-black uppercase tracking-widest rounded-full shadow-[0_0_20px_rgba(0,255,102,0.3)] hover:shadow-[0_0_30px_rgba(0,255,102,0.5)] transition-all flex items-center justify-center gap-2"
            >
              {loadingPlan === "growth" ? "Initiating..." : "Start Increasing Revenue"} <Zap size={20} fill="currentColor" />
            </button>
          </div>

          {/* SCALE */}
          <div className="bg-[#050805] border border-[#222] rounded-3xl p-8 shadow-[0_0_20px_rgba(0,0,0,0.5)] flex flex-col justify-between group hover:border-[#00ff66]/40 transition-colors">
            <div>
              <h3 className="text-2xl font-bold text-white mb-2">Scale</h3>
              <p className="text-gray-400 text-sm mb-6 h-10">Enterprise architecture with aggressive causal modeling algorithms.</p>
              
              <div className="my-6 space-y-1">
                <div className="text-5xl font-black text-white tracking-tighter">$299<span className="text-xl text-gray-500 font-normal">/mo</span></div>
                <div className="text-[#ff3333] font-bold text-lg">+ 30% Performance Share</div>
              </div>

              <ul className="space-y-4 mb-8">
                <li className="flex items-start gap-3"><CheckCircle size={20} className="text-[#00ff66] shrink-0 mt-0.5" /> <span className="text-gray-300 text-sm">Unlimited Causal Models</span></li>
                <li className="flex items-start gap-3"><CheckCircle size={20} className="text-[#00ff66] shrink-0 mt-0.5" /> <span className="text-gray-300 text-sm">Whitelabel Engine Bypass</span></li>
                <li className="flex items-start gap-3"><CheckCircle size={20} className="text-[#00ff66] shrink-0 mt-0.5" /> <span className="text-gray-300 text-sm">Dedicated AI Integration Node</span></li>
              </ul>
            </div>
            
            <button 
              onClick={() => startCheckout("scale")}
              disabled={loadingPlan !== null}
              className="w-full py-4 bg-[#111] hover:bg-[#222] text-white font-bold rounded-full border border-[#333] transition-colors flex items-center justify-center gap-2"
            >
              {loadingPlan === "scale" ? "Initiating..." : "Start Increasing Revenue"} <ArrowRight size={18} />
            </button>
          </div>

        </div>

        {/* TRUST LAYER */}
        <div className="bg-[#050505] border border-[#222] rounded-2xl p-8 flex flex-col md:flex-row items-center justify-around gap-8 text-left max-w-4xl mx-auto">
          <div className="flex items-start gap-4">
            <Shield size={32} className="text-[#00ff66] mt-1" />
            <div>
              <h4 className="font-bold text-white mb-1">Transparent AI Attribution</h4>
              <p className="text-gray-400 text-sm leading-relaxed">No black boxes. We only take a commission if our system is undeniably responsible for saving a lost cart or lifting a conversion.</p>
            </div>
          </div>
          <div className="flex items-start gap-4">
            <Brain size={32} className="text-[#00ff66] mt-1" />
            <div>
              <h4 className="font-bold text-white mb-1">No-Risk Architecture</h4>
              <p className="text-gray-400 text-sm leading-relaxed">If the engine fails to generate any incremental revenue, you only pay the baseline fixed infrastructure cost. Stripe handles the metered usage automatically.</p>
            </div>
          </div>
        </div>

        {/* CTO AUDIT: LEGAL TRANSPARENCY DEFINITION */}
        <div className="mt-12 text-left border-t border-[#222] pt-8 max-w-4xl mx-auto">
          <h5 className="text-gray-400 font-bold mb-2 uppercase tracking-wide text-sm">Strict Legal Definition of Incremental Revenue:</h5>
          <p className="text-gray-500 text-xs leading-relaxed">
            Incremental revenue is defined strictly as gross sales generated from a user who completed a purchase within exactly 60 minutes of interacting with a Zeno AI-driven conversion action (e.g. discount unlock, urgency trigger). Users who initiated checkout prior to AI intervention are severely discounted in attribution weight (80% reduction) to ensure extreme fairness. Refunds are dynamically synchronized with Stripe and deducted from the billing cycle automatically using strict Idempotency processing over PostgreSQL.
          </p>
        </div>

      </main>
    </div>
  );
}
